# hydra_ray_tune_sweeper/conf/hydra/sweeper/search_alg/ax.yaml
# @package hydra.sweeper.search_alg
_target_: ray.tune.search.ax.AxSearch
metric: null
mode: "min"
parameter_constraints: null
outcome_constraints: null

